### ISSUE TITLE
libgit2 won't load on Linux

### ISSUE THREAD

**Issue by theseion** [theseion/LibGit#11]
NativeBoost can't load the libgit2 library on Linux. Should check if the library is being built / linked correctly.

**Comment by theseion** [comment]
Fix is in the pipline. We're waiting for the CI to come back up.

**Comment by theseion** [comment]
works on debian.

**Comment by theseion** [comment]
Tested latest build on Ubuntu: still failed.
Same goes for the latest VM built on debian.

**Comment by theseion** [comment]
We now have a Linux build on the CI and it works :)

**Comment by tinchodias** [comment]
Yeah!
