### ISSUE TITLE
Use handle instead of library name for function access

### ISSUE THREAD

**Issue by theseion** [theseion/LibGit#13]
Currently every function lookup is performed by passing the module name of the library first. Rather pass the handle after first use.

**Comment by tinchodias** [comment]
What's the consequence of this change? it's nicer? faster?

**Comment by theseion** [comment]
It should be slightly faster (neglegible). But it prevents the vm from running the module lookup routine and instead makes NB use the symbol lookup directly. So it’s “nicer” (but not if you look at my code… not polished yet.).

**Comment by tinchodias** [comment]
ok ;)
