### ISSUE TITLE
Can't create a LGitTreeBuilder

### ISSUE THREAD

**Issue by tinchodias** [theseion/LibGit#21]
Got "An instance of LGitTree expected".

Basically, this code fails:

	builder := LGitTreeBuilder of: repo.
	builder createNew.

The error is already reproduced in:

	LGitTreeBuilderTest>>#testAddEntry

**Comment by theseion** [comment]
I have to fix the configuration. What you need to do is load the latest NativeBoost package from the inbox and then execute `NativeBoost clearNativeCode`.

**Comment by tinchodias** [comment]
Thanks!
