### ISSUE TITLE
Structs allocated from the image can't be freed with the provided functions

### ISSUE THREAD

**Issue by theseion** [theseion/LibGit#24]
See LGitIndex>>updateAll and #addAll and #removeAll. Need to free the address of the struct and not use the provided free function of the struct.
Otherwise we'll see error messages on stdout. 

Problem: this only frees the struct but does not tear down internals.

**Comment by theseion** [comment]
The problem is that memory is being managed by NativeBoost with `mmap` and `munmap`. The C standard clearly states that `free` may only be used for pointers allocated with `malloc`, `realloc` or `calloc`. 
So for all memory allocated from the image, it is mandatory to use the NativeBoost `free` function. 

I need to revise the finalization scheme structs.

**Comment by tinchodias** [comment]
Done?! Wow (a la mierda! :-) )

**Comment by theseion** [comment]
> On 16.07.2015, at 21:37, Martín Dias <notifications@github.com> wrote:
> 
> Done?! Wow (a la mierda! :-) )
> El 16/7/2015 15:36, "Max Leske" <notifications@github.com> escribió:

A la mierda!! 😁
