### ISSUE TITLE
should be using BaselineOfLibGit

### ISSUE THREAD

**Issue by dalehenrich** [theseion/LibGit#26]
@theseion if you were using a BaselineOf I think that things would be much cleaner ... there's not much advantage to using a ConfigurationOf for a GitHub-based project ... 

I could give you a pull request with a BaselineOf, based on your current CofigurationOf if you'd like ...

**Comment by theseion** [comment]
Yes please!

**Comment by dalehenrich** [comment]
Okey dokey ... I'll see what I can do:)

**Comment by theseion** [comment]
Thanks Dale. I'll check it out later.

**Comment by dalehenrich** [comment]
No hurry ... if you have questions comment, try making inline comments on PR (https://github.com/theseion/LibGit/pull/27/files)

**Comment by theseion** [comment]
Very cool Dale, thanks!
I've ditched the ConfigurationOf in favor of the BaselineOf.

**Comment by tinchodias** [comment]
Hi Dale and Max,

I have a project that depends on LibGit. In the ConfigurationOf, I changed to:

```Smalltalk
		spec 
			project: 'LibGit' with: [
				spec
					baseline: #LibGit; 
					repository: 'github://theseion/LibGit:master' ].
```

from:

```Smalltalk
		spec 
			project: 'LibGit' with: [
				spec
					className: #ConfigurationOfLibGit;
					versionString: #'bleedingEdge';
					repository: 'http://smalltalkhub.com/mc/FileSystemGitDev/LibGit2/main/' ].
```

**Comment by theseion** [comment]
Great! Does it work?

**Comment by tinchodias** [comment]
Ooops, you answered too fast, while I was editing my post :) 

Strangely, it loads fine when doing directly "ConfigurationOfYrupe loadBleedingEdge", but it doesn't load when doing "ConfigurationOfFicus loadBleedingEdge", which depends on ConfigurationOfYrupe.

So, to make it more clear, the dependencies are:

Yrupe -> Ficus -> LibGit

**Comment by theseion** [comment]
Solved.
