### ISSUE TITLE
add diff bindings

### ISSUE THREAD

**Issue by theseion** [theseion/LibGit#31]
The information that I need at the moment is for each commit from the history:
- get a list of all diff segments
- for each segment get the from - to interval for the added / deleted / modified lines
- for each segment get the concrete added/deleted/modified text

So, I would need the information as objects. Maybe something like this: Commit ->* DiffSegment (which holds, oldInterval, newInterval, newText).

**Comment by tinchodias** [comment]
cool!

**Comment by theseion** [comment]
Doru requested this. I'll try to get it done this week.

**Comment by tinchodias** [comment]
what is missing to close this issue?

**Comment by theseion** [comment]
Nothing I think... Closing.
