### ISSUE TITLE
Failed to commit and push a MC version

### ISSUE THREAD

**Issue by tinchodias** [theseion/LibGit#32]
When I fixed a small typo in LibGit and tried to commit it using the MC UI, I got this error:

![screen shot 2015-06-26 at 14 14 13](https://cloud.githubusercontent.com/assets/3044265/8377895/9a2d5ade-1c15-11e5-8745-a651382eee94.png)

But I think I already committed a change, some time ago... did I?

**Comment by theseion** [comment]
This has to do with the use of external arrays which don't hold on to the data. I need to rewrite that.
