### ISSUE TITLE
Decode from utf8 when reading strings?

### ISSUE THREAD

**Issue by tinchodias** [theseion/LibGit#33]
I use "Martín Dias" in my signature, which is displayed like:

![screen shot 2015-06-26 at 15 22 10](https://cloud.githubusercontent.com/assets/3044265/8378099/22cd96c8-1c17-11e5-84bf-af54500be575.png)

When utf8Decoded, it still looks wrong inside Pharo, but when I copy&paste the string here, it looks fine: "'Martín Dias'"

Magic? :-p  I'm ignorant about utf8.

**Comment by dalehenrich** [comment]
@tinchodias it just so happens that I'm working with UTF8, so here's some information:

```
.            -> 'Martín Dias'
(bytes)@     -> #[ 77 97 114 116 237 110 32 68 105 97 115]
(utf8)@      -> #[ 77 97 114 116 195 173 110 32 68 105 97 115]
```

The bytes are the code points and the `í`is codePoint 237 ... The uft8 is the utf8 encoding ... 

So you need to look at the code points in the "wrong pharo string" to figure out what might be wrong ... also look at the code points in the name (pre-utfDecoded) ... code points at the point that you are encoding things and writing to disk would complete the picture

In my pharo image using the `WenQuanYi Micro Hei mono font`, the utf8 encode string looks like this:

![mertindias](https://cloud.githubusercontent.com/assets/623951/8419030/bba0c7f2-1e6b-11e5-9302-23850be63234.png)

Which is not quite what you've got, but different fonts display things differently ...

**Comment by theseion** [comment]
The encoding is correct and it's UTF-8. When you paste the string into the image it becomes ISO encoded (the 'i' has the ASCII byte 237).
The thing is, there are two different ways of encoding you name in UTF-8:
- with LATIN SMALL LETTER I WITH GRAVE (http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=128)
- with regular 'i' + COMBINING ACUTE ACCENT (http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=640)

Pharo can't seem to display either encoding (at least not in my font). Not all fonts define glyphs for all combinations of characters.

Just so you know, Unicode publishes algorithms for reducing encodings to a "normal form", which usually means the shortest possible form.

**Comment by tinchodias** [comment]
Thanks for the complete answers. After another look, I discovered that ```aSignature name  asByteArray``` answers a different sequence (I aligned the bytes to visualize better). It has an extra byte:

```
(MINE)@      -> #[ 77 97 114 116 105 204 129 110 32 68 105 97 115]
(bytes)@     -> #[ 77 97 114 116 237         110 32 68 105 97 115]
(utf8)@      -> #[ 77 97 114 116 195 173     110 32 68 105 97 115]
```

**Comment by dalehenrich** [comment]
@theseion given that I believe the code point is 237, the character is `LATIN SMALL LETTER I WITH ACUTE`

@tinchodias assuming that `(MINE)@` is the result of sending #decodeUtf8 to the *proper* utf8 bytes, the utf8 decode algorithm must be flawed...

**Comment by theseion** [comment]
@dalehenrich Yes, you're right of course. I copied the wrong line :)
The representation is valid UTF-8, regardless. From that point of view the decoding works fine. However, the UTF-8 result may not be in "normal form". Here's the Unicode FAQ on the matter: http://unicode.org/faq/normalization.html

Not all fonts contain all glyphs to display all combinations of UTF-8 encodings, therefore a given font my correctly display the two byte form but not the 'i' + two byte form (or vice-versa). In my opinion it really comes down to font support in Pharo since you can't assume anything about the encoding of strings that come from another system (and with Git they can come from anywhere; UTF-8 isn't even required)

**Comment by dalehenrich** [comment]
@theseion I am wondering why the utf8 decoder doesn't produce codePoint 237 .. I am using utf8 encoding in Pharo for tODE and 'Martín Dias' is handled correctly in my case ... the fact that @tinchodias is seeing a different set of codePoints is odd and I suspect the utf8 decoder ...

**Comment by tinchodias** [comment]
@dalehenrich The "mine" bytes were not utf8 decoded... Just my name asByteString

**Comment by tinchodias** [comment]
Sorry: asByteArray

**Comment by theseion** [comment]
@dalehenrich So did you read the ```#[ 77 97 114 116 105 204 129 110 32 68 105 97 115]``` sequence (that's the sequence from the commit) and get ```#[ 77 97 114 116 237         110 32 68 105 97 115]```? I get that exact sequence (the former one) in Pharo, which is good I think. No implicit conversion to another encoding. The only thing left would be to have a font to display the glyphs.

**Comment by dalehenrich** [comment]
The results I was getting on both pharo and Gemstone was described [here](https://github.com/theseion/LibGit/issues/33#issuecomment-116853256) ...  your first series is the utf8 encoded bytes and your second series is the decoded bytes and yours matches with my results in both pharo and GemStone ...

Still a mystery why @tinchodias is getting different results for his name ...

Decoding in GemStone:

```Smalltalk
#[ 77 97 114 116 105 204 129 110 32 68 105 97 115] decodeFromUTF8
```

I get the following code points (note in GemStone) :

```Smalltalk
#[ 0 77 0 97 0 114 0 116 0 105 3 1 0 110 0 32 0 68 0 105 0 97 0 115]
```

and the same funky font display as @tinchodias observes ... I also observe that if I paste the String copied from Pharo into Chrome that the string looks correct: `'Martín Dias'`.

When I look closeley at the two strings in GemStone they are obviously different. 

Here's the `good String`:

```
.            -> 'Martín Dias'
(class)@     -> String
(oop)@       -> 188507649
(invariant)@ -> true
(size)@      -> 11
(bytes)@     -> #[ 77 97 114 116 237 110 32 68 105 97 115]
(utf8)@      -> #[ 77 97 114 116 195 173 110 32 68 105 97 115]
1@           -> $M
2@           -> $a
3@           -> $r
4@           -> $t
5@           -> $í
6@           -> $n
7@           -> $ 
8@           -> $D
9@           -> $i
10@          -> $a
11@          -> $s
```

and here's the `bad string`:

```
.            -> 'Martín Dias'
(class)@     -> DoubleByteString
(oop)@       -> 211797505
(invariant)@ -> true
(size)@      -> 12
(bytes)@     -> #[ 0 77 0 97 0 114 0 116 0 105 3 1 0 110 0 32 0 68 0 105 0 97 0 115]
(utf8)@      -> #[ 77 97 114 116 105 204 129 110 32 68 105 97 115]
1@           -> $M
2@           -> $a
3@           -> $r
4@           -> $t
5@           -> $i
6@           -> $́
7@           -> $n
8@           -> $ 
9@           -> $D
10@          -> $i
11@          -> $a
12@          -> $s
```

Note that the `bad one` decodes as a DoubleByteString and the good one decodes as a String, which implies the the `i` in the bad one has a code point > 255 ... which is presumably the `COMBINING ACUTE ACCENT` as @theseion pointed out earlier .... 

I was confused earlier in the discussion by the following:

```
(MINE)@      -> #[ 77 97 114 116 105 204 129 110 32 68 105 97 115]
(bytes)@     -> #[ 77 97 114 116 237         110 32 68 105 97 115]
(utf8)@      -> #[ 77 97 114 116 195 173     110 32 68 105 97 115]
```

and I **thought** that @tinchodias was claiming the the `bytes` and `utf8` fields were from  **his** string, not copies of what I had sent earlier:) so I went down a rabbit hole ...

this is just a Pharo font problem at the end of the day ....

**Comment by theseion** [comment]
Thanks for the explanation.
I just discovered my own rabbit hole: ```signature name asByteArray utf8Decoded``` yields a WideString where one double byte has the value 769... I have no clue what that is supposed to encode for but this is what it looks like:
![screen shot 2015-07-03 at 07 01 49](https://cloud.githubusercontent.com/assets/250711/8492870/8ee6b800-2151-11e5-9be9-df662ef68a45.png)

Note that there are two different fonts in the image :)
So it may be that there is indeed something strange going on with UTF-8 decoding in certain cases, but then again, there's no sensible conversion for all UTF-8 glyphs to ASCII. Let's get someone to implement proper font support :)

**Comment by dalehenrich** [comment]
@theseion ... utf8 is an encoding that encodes unicode characters (7-bit, 16-bit and 32-bit) in 8-bit chunks  for transit ... the problem with a wide string converted directly to bytes, is that you do not know whether to decode them back use 1, 2 or 4 bytes per character ... when you decode a utf8 encoded string, a new String is produced preserving each of the code points  ... Sooooo

In your case the codePoint 769 (which turns out to your U+0301 character[](http://www.fileformat.info/info/unicode/char/0301/index.htm)take two bytes to represent (and is the reason that you've ended up with a WideString) ... if you encode that string as utf8 and then decode it again you should end up with the same set of codePoints...

**Comment by dalehenrich** [comment]
...the fonts that you have installed in Pharo do not have a glyph for U+301, or are interpreting the U+301 as two distinct characters ...
