### ISSUE TITLE
Error when reading blob binary contents

### ISSUE THREAD

**Issue by tinchodias** [theseion/LibGit#9]
My image was crashing when executing LGtBlob>>contents of a blob with binary content. (I checked that it answers true to LGtBlob>>isBinary)

My blob had this content:

	'SUnit tests for fuel serializations, here signatures$$'

Where $ is the ascii character 5 (i.e. insert).

Weird. I tried modifying the current  #testBinary with my particular string and there is no problem. But in my scenario was 100% reproducible.

**Comment by theseion** [comment]
Not reproducible.
